const iconTypes = {
  ACCOUNT: 'ACCOUNT',
  ARROWDOWN: 'ARROWDOWN',
  ARROWLEFT: 'ARROWLEFT',
  ARROWRIGHT: 'ARROWRIGHT',
  CALENDAR: 'CALENDAR',
  CLEAR: 'CLEAR',
  CLOSE: 'CLOSE',
  DELETE: 'DELETE',
  DONE: 'DONE',
  EDIT: 'EDIT',
  FLAG: 'FLAG',
  HELP: 'HELP',
  INFO: 'INFO',
  LAUNCH: 'LAUNCH',
  LOGOUT: 'LOGOUT',
  MANAGE: 'MANAGE',
  MORE: 'MORE',
  PLUS: 'PLUS',
  SEARCH: 'SEARCH',
  SETTINGS: 'SETTINGS',
};

export default iconTypes;
